In [ ]:
from transformers import AutoTokenizer
import torch


In [ ]:
pip install requests==2.27.1  
import os
os.environ['CURL_CA_BUNDLE'] = ''

In [3]:
model_='bert-based-uncased'
text='time files like an arrow'

In [7]:
from transformers import AutoTokenizer
model_ckpt = "bert-base-uncased"
text = "time flies like an arrow"
tokenizer = AutoTokenizer.from_pretrained(model_ckpt)

C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:147: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\jv028u\.cache\huggingface\hub\models--bert-base-uncased. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpoo

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(
C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [8]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=False),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [9]:
inputs = tokenizer(text, return_tensors="pt", add_special_tokens=False)

In [10]:
input_ids = inputs.input_ids

In [11]:
input_ids

tensor([[ 2051, 10029,  2066,  2019,  8612]])

### 2. *Embedding*

In [14]:
from torch import nn
from transformers import AutoConfig
config=AutoConfig.from_pretrained(model_ckpt)
token_emb=nn.Embedding(config.vocab_size,config.hidden_size)
input_embeds=token_emb(inputs.input_ids)

C:\Users\jv028u\AppData\Local\Programs\Python\Python312\Lib\site-packages\urllib3\connectionpool.py:1064: InsecureRequestWarning: Unverified HTTPS request is being made to host 'huggingface.co'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


*AutoConfig:* loads the configuration for the BERT model,includes important hyperparameters like vocab_size (30522 tokens) and hidden_size (768).

nn.Embedding:*  creates an embedding layer.  input token ID is mapped to a high-dimensional vector (768-dimensional in BERT's case).

inputs_embeds:* Here, input token IDs are passed through the embedding layer, converting each token ID into a dense vector of size [768]. These are raw, non-contextual embeddings that do not yet include any position or sequence information.




In [47]:
input_embeds

tensor([[[ 0.6435,  0.9685,  0.2010,  ...,  0.0762, -0.5175, -0.7158],
         [-1.9802, -0.0077,  1.6865,  ..., -0.0394, -0.2377, -1.7966],
         [-0.6890, -1.3175, -0.8030,  ..., -2.6974,  0.1425, -0.6903],
         [ 0.1641,  1.7179, -0.8291,  ...,  1.8245, -1.2870, -0.3912],
         [-1.1103, -0.0307, -0.2500,  ..., -1.3880,  1.3403,  1.4526]]],
       grad_fn=<EmbeddingBackward0>)

### 3. *Attention Mechanism: Scaled Dot Product*

In [22]:
import torch
from math import sqrt 

query=key=value=input_embeds
dim_k=key.size(-1)

scores=torch.bmm(query,key.transpose(1,2))/sqrt(dim_k)

In [36]:
query.size(), key.transpose(1,2).size()

(torch.Size([1, 5, 768]), torch.Size([1, 768, 5]))

In [37]:
 scores.dim()

3

In [23]:
scores 
#relation of words. influence of other words  to enecode particular word

tensor([[[30.9423, -0.3590,  0.0889,  0.5369,  0.6388],
         [-0.3590, 24.8945,  2.2607,  0.0989, -0.2881],
         [ 0.0889,  2.2607, 27.0244,  0.5362, -0.2460],
         [ 0.5369,  0.0989,  0.5362, 28.6788, -2.3923],
         [ 0.6388, -0.2881, -0.2460, -2.3923, 28.3938]]],
       grad_fn=<DivBackward0>)

### 4. *Attention Weights (Softmax)*

In [24]:
import torch.nn.functional as F
weights = F.softmax(scores, dim=-1)


In [25]:
weights 
#determine % of each input word should be used to encode word 

tensor([[[1.0000e+00, 2.5470e-14, 3.9861e-14, 6.2389e-14, 6.9086e-14],
         [1.0778e-11, 1.0000e+00, 1.4800e-10, 1.7037e-11, 1.1570e-11],
         [2.0048e-12, 1.7591e-11, 1.0000e+00, 3.1358e-12, 1.4342e-12],
         [5.9998e-13, 3.8718e-13, 5.9958e-13, 1.0000e+00, 3.2063e-14],
         [8.8339e-13, 3.4962e-13, 3.6463e-13, 4.2632e-14, 1.0000e+00]]],
       grad_fn=<SoftmaxBackward0>)

### 5. *Weighted Sum: Update Embeddings*

In [28]:
attn_outputs=torch.bmm(weights,value)

In [38]:
attn_outputs.size()

torch.Size([1, 5, 768])

- *torch.bmm:* Now that we have attention weights, we multiply them with the value vectors. This produces new embeddings where each word's representation is updated based on how much it attends to others.
- gives context to each word  and realtion b/w words .
- If the word "flies" pays 80% attention to "time," its new embedding will be largely influenced by "time."

In [29]:
attn_outputs  # Each score represents how much attention should be paid to other tokens in the sequence.

tensor([[[ 0.6435,  0.9685,  0.2010,  ...,  0.0762, -0.5175, -0.7158],
         [-1.9802, -0.0077,  1.6865,  ..., -0.0394, -0.2377, -1.7966],
         [-0.6890, -1.3175, -0.8030,  ..., -2.6974,  0.1425, -0.6903],
         [ 0.1641,  1.7179, -0.8291,  ...,  1.8245, -1.2870, -0.3912],
         [-1.1103, -0.0307, -0.2500,  ..., -1.3880,  1.3403,  1.4526]]],
       grad_fn=<BmmBackward0>)

In [ ]:
def scaled_dot_product_attention(query, key, value):
    dim_k = query.size(-1)
    scores = torch.bmm(query, key.transpose(1, 2)) / sqrt(dim_k)
    weights = F.softmax(scores, dim=-1) # # apply softmax along the last dimension of tensor, i.e., dimension of embedding features
    return torch.bmm(weights, value)

### 6. *Attention Head*
implements a single attention head in a Transformer model using PyTorch. 


In [41]:
# create a class for one attention head
class AttentionHead(nn.Module):
    # initialize the class
    def __init__(self, embed_dim, head_dim): # embed_dim=768, head_dim=64 -number of dimensions we want to project the hidden state to
        # call the parent class
        super().__init__()
        # create the linear transformation layers
        self.q = nn.Linear(embed_dim, head_dim) # project (1, 5, 768) -> (1, 5, 64)
        self.k = nn.Linear(embed_dim, head_dim) # project (1, 5, 768) -> (1, 5, 64)
        self.v = nn.Linear(embed_dim, head_dim) # project (1, 5, 768) -> (1, 5, 64)

    # define the forward pass of the class
    def forward(self, hidden_state):                         # hidden_state.size() = inputs_embeds.size() = (1, 5, 768) = (batch_size, seq_len, hidden_size) 
        # calculate the scaled dot product attention for one head 
        dim_k = self.k(hidden_state).size(-1)                # get the last dimension of the key after linear transformation   (1, 5, 64) -> 64
        scores = torch.bmm(self.q(hidden_state),             # calculate the attention scores (1, 5, 64) * (1, 64, 5) = (1, 5, 5)
                           self.k(hidden_state).transpose(1,2)) / sqrt(dim_k) 
        attn_weights = F.softmax(scores, dim=-1)             # calculate the attention weights (1, 5, 5)
        return torch.bmm(attn_weights, self.v(hidden_state)) # return the attention outputs (1, 5, 5) * (1, 5, 64) = (1, 5, 64)


In [45]:
# create a class for the multi-head attention

class MultiHeadAttention(nn.Module):
    # initialize the class
    def __init__(self, config):
        # call the parent class
        super().__init__()
        
        # create the attention heads
        embed_dim = config.hidden_size         # 768
        num_heads = config.num_attention_heads # 12
        head_dim = embed_dim // num_heads      # 64

        # create the attention heads
        self.heads = nn.ModuleList(
            [AttentionHead(embed_dim, head_dim) for _ in range(num_heads)] # create 12 attention heads where each K,V,Q is of size 64
        )
        # create the output linear transformation
        self.output_linear = nn.Linear(embed_dim, embed_dim)
        
    # define the forward pass
    def forward(self, hidden_state):           # hidden_state.size() = inputs_embeds.size() = (1, 5, 768) = (batch_size, seq_len, hidden_size)
        # concatenate the attention outputs of the 12 attention heads
        x = torch.cat([h(hidden_state) for h in self.heads], dim=-1)
        # apply the output linear transformation
        x = self.output_linear(x)
        return x


In [49]:
multihead_attn = MultiHeadAttention(config)
attn_output = multihead_attn(input_embeds)    
attn_output.size() 

torch.Size([1, 5, 768])

In [50]:
multihead_attn

MultiHeadAttention(
  (heads): ModuleList(
    (0-11): 12 x AttentionHead(
      (q): Linear(in_features=768, out_features=64, bias=True)
      (k): Linear(in_features=768, out_features=64, bias=True)
      (v): Linear(in_features=768, out_features=64, bias=True)
    )
  )
  (output_linear): Linear(in_features=768, out_features=768, bias=True)
)

In [56]:

# # This step helps to visualize how each token in the input attends to other tokens.
from bertviz import head_view
from transformers import AutoModel

model=AutoModel.from_pretrained(model_ckpt,output_attentions=True)

sentence_a = "time flies like an arrow"
sentence_b = "fruit flies like a banana"

viz_inputs=tokenizer(sentence_a,sentence_b,return_tensors='pt')
attention=model(**viz_inputs).attentions

sentence_b_start = (viz_inputs.token_type_ids == 0).sum(dim=1)
tokens=tokenizer.convert_ids_to_tokens(viz_inputs.input_ids[0])

head_view(attention,tokens,sentence_b_start,heads=[8])

### *The Feed-Forward Layer*


 two-layer fully connected neural network, but with a twist: instead of processing the whole sequence of embeddings as a single vector, it processes each embedding indepenentl

In [54]:
# create a class for the point-wise feed forward network
class FeedForward(nn.Module):
    # initialize the class
    def __init__(self, config):                                  
        # call the parent class
        super().__init__()
        self.linear_1 = nn.Linear(config.hidden_size, config.intermediate_size) # project (1, 5, 768) -> (1, 5, 3072)
        self.linear_2 = nn.Linear(config.intermediate_size, config.hidden_size) # project (1, 5, 3072) -> (1, 5, 768)
        self.gelu = nn.GELU()                                                   # use the GELU activation function
        self.dropout = nn.Dropout(config.hidden_dropout_prob)                   # use the dropout probability from the config
    
    # define the forward pass of the Forward class
    def forward(self, x):
        x = self.linear_1(x)
        x = self.gelu(x)
        x = self.linear_2(x)
        x = self.dropout(x)
        return x
        


In [55]:
attn_outputs.size()


torch.Size([1, 5, 768])

In [57]:
feed_forward = FeedForward(config)
ff_outputs = feed_forward(attn_outputs)
ff_outputs.size()

torch.Size([1, 5, 768])

### *Adding Layer Normalization*

Transformer Encoder Layer with Layer Normalization
- Each transformer encoder layer consists of two sub-layers: multi-head attention and a feed-forward layer.
- *Layer Normalization* is applied before these sub-layers to stabilize and normalize the inputs.
- 

In [59]:
class TransformerEncoderLayer(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.layer_norm_1 = nn.LayerNorm(config.hidden_size)
        self.layer_norm_2 = nn.LayerNorm(config.hidden_size)
        self.attention = MultiHeadAttention(config)
        self.feed_forward = FeedForward(config)

    def forward(self, x):
        hidden_state = self.layer_norm_1(x)
        x = x + self.attention(hidden_state)
        x = x + self.feed_forward(self.layer_norm_2(x))
        return x


In [62]:
encoder_layer = TransformerEncoderLayer(config)
input_embeds.shape, encoder_layer(input_embeds).size()

(torch.Size([1, 5, 768]), torch.Size([1, 5, 768]))

### *Embedding Layer (Token + Positional Embeddings)*

In [63]:
# create a class for embedding layer that combines token and position embeddings
# position embeddings are learnable
class Embeddings(nn.Module):
    # initialize the class
    def __init__(self, config):
        # call the parent class
        super().__init__()

        # create the token and position embeddings 
        self.token_embeddings = nn.Embedding(config.vocab_size,     # 30522, the size of the vocabulary
                                             config.hidden_size)    # 768, the hidden size of the model
        self.position_embeddings = nn.Embedding(config.max_position_embeddings, # 512, maximum sequence length that this model might ever be used with
                                                config.hidden_size)             # 768, the hidden size of the model
        self.layer_norm = nn.LayerNorm(config.hidden_size, eps=1e-12)            
        self.dropout = nn.Dropout()

    # define the forward pass of the embedding layer
    def forward(self, input_ids):                                              # tensor([[ 2051, 10029,  2066,  2019,  8612]])
        # Create position IDs for input sequence
        seq_length = input_ids.size(1)                                         # 5
        position_ids = torch.arange(seq_length, dtype=torch.long).unsqueeze(0) # tensor([[0, 1, 2, 3, 4]])
        # Create token and position embeddings
        token_embeddings = self.token_embeddings(input_ids)
        position_embeddings = self.position_embeddings(position_ids)
        # Combine token and position embeddings
        embeddings = token_embeddings + position_embeddings
        embeddings = self.layer_norm(embeddings)
        embeddings = self.dropout(embeddings)
        return embeddings

In [64]:
# instantiate the embedding layer
embedding_layer = Embeddings(config)
# apply the embedding layer to the input_ids
embedding_layer(inputs.input_ids).size()

torch.Size([1, 5, 768])

### *Full Transformer Encoder*

In [65]:
class TransformerEncoder(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.embeddings = Embeddings(config)
        self.layers = nn.ModuleList([TransformerEncoderLayer(config) for _ in range(config.num_hidden_layers)])
    
    def forward(self, x):
        x = self.embeddings(x)
        for layer in self.layers:
            x = layer(x)
        return x



### *Classification Head*

In [66]:
class TransformerForSequenceClassification(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.encoder = TransformerEncoder(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.classifier = nn.Linear(config.hidden_size, config.num_labels)

    def forward(self, x):
        x = self.encoder(x)[:, 0, :]
        x = self.dropout(x)
        x = self.classifier(x)
        return x


### *Masked Attention in Decoder*

In [67]:
def scaled_dot_product_attention(query, key, value, mask=None):
    dim_k = query.size(-1)
    scores = torch.bmm(query, key.transpose(1, 2)) / sqrt(dim_k)
    if mask is not None:
        scores = scores.masked_fill(mask == 0, float("-inf"))
    weights = F.softmax(scores, dim=-1)
    return weights.bmm(value)

